FROM ruby:4.0.2-slim

RUN apt-get update -qq && \
    apt-get install -y --no-install-recommends \
      build-essential libpq-dev libvips-dev libyaml-dev \
      curl git nodejs npm \
      && rm -rf /var/lib/apt/lists/*

RUN npm install -g n && n 25 && npm install -g yarn

WORKDIR /app

COPY Gemfile Gemfile.lock .ruby-version ./
RUN bundle install --jobs 4

COPY package.json yarn.lock ./
RUN yarn install

RUN gem install foreman

COPY . .
RUN cp config/database.docker.yml config/database.yml

CMD ["bash", "-c", "bundle install --quiet && rm -f tmp/pids/server.pid && bin/rails db:migrate && foreman start -f Procfile.dev.docker"]
